# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '3'

services:
  redis:
    image: docker.io/bitnami/redis:7.2
    container_name: redis
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    network_mode: host
    ports:
      - '6379:6379'
  redis-slave-1:
    image: docker.io/bitnami/redis:7.2
    container_name: redis-slave-1
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=localhost
      - REDIS_PORT_NUMBER=6380
      - ALLOW_EMPTY_PASSWORD=yes
    network_mode: host
    ports:
      - '6380:6380'
  redis-slave-2:
    image: docker.io/bitnami/redis:7.2
    container_name: redis-slave-2
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=localhost
      - REDIS_PORT_NUMBER=6381
      - ALLOW_EMPTY_PASSWORD=yes
    network_mode: host
    ports:
      - '6381:6381'
  redis-sentinel-1:
    image: docker.io/bitnami/redis-sentinel:7.2
    environment:
      - REDIS_MASTER_HOST=localhost
      - REDIS_SENTINEL_PORT_NUMBER=26379
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=1000
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_SENTINEL_RESOLVE_HOSTNAMES=yes
      - REDIS_SENTINEL_QUORUM=2
      - ALLOW_EMPTY_PASSWORD=yes
    network_mode: host
    depends_on:
      - redis
      - redis-slave-1
      - redis-slave-2
    ports:
      - '26379:26379'
  redis-sentinel-2:
    image: docker.io/bitnami/redis-sentinel:7.2
    environment:
      - REDIS_MASTER_HOST=localhost
      - REDIS_SENTINEL_PORT_NUMBER=26380
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=1000
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_SENTINEL_RESOLVE_HOSTNAMES=yes
      - REDIS_SENTINEL_QUORUM=2
      - ALLOW_EMPTY_PASSWORD=yes
    network_mode: host
    depends_on:
      - redis
      - redis-slave-1
      - redis-slave-2
    ports:
      - '26380:26380'
  redis-sentinel-3:
    image: docker.io/bitnami/redis-sentinel:7.2
    environment:
      - REDIS_MASTER_HOST=localhost
      - REDIS_SENTINEL_PORT_NUMBER=26381
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=1000
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_SENTINEL_RESOLVE_HOSTNAMES=yes
      - REDIS_SENTINEL_QUORUM=2
      - ALLOW_EMPTY_PASSWORD=yes
    network_mode: host
    depends_on:
      - redis
      - redis-slave-1
      - redis-slave-2
    ports:
      - '26381:26381'


